[2019-07-22 16:00:34,713: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-22 16:00:34,730: INFO/MainProcess] mingle: searching for neighbors
[2019-07-22 16:00:35,759: INFO/MainProcess] mingle: all alone
[2019-07-22 16:00:35,783: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-22 16:00:35,783: INFO/MainProcess] celery@lwt.local ready.
[2019-07-22 16:05:48,735: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-22 16:05:48,746: INFO/MainProcess] mingle: searching for neighbors
[2019-07-22 16:05:49,777: INFO/MainProcess] mingle: all alone
[2019-07-22 16:05:49,804: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-22 16:05:49,805: INFO/MainProcess] celery@lwt.local ready.
[2019-07-22 16:10:05,106: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-22 16:10:05,115: INFO/MainProcess] mingle: searching for neighbors
[2019-07-22 16:10:06,144: INFO/MainProcess] mingle: all alone
[2019-07-22 16:10:06,170: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-22 16:10:06,171: INFO/MainProcess] celery@lwt.local ready.
[2019-07-22 16:32:30,058: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-22 16:32:30,072: INFO/MainProcess] mingle: searching for neighbors
[2019-07-22 16:32:31,104: INFO/MainProcess] mingle: all alone
[2019-07-22 16:32:31,138: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-22 16:32:31,138: INFO/MainProcess] celery@lwt.local ready.
[2019-07-22 16:35:25,893: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-22 16:35:25,907: INFO/MainProcess] mingle: searching for neighbors
[2019-07-22 16:35:26,947: INFO/MainProcess] mingle: all alone
[2019-07-22 16:35:26,983: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-22 16:35:26,983: INFO/MainProcess] celery@lwt.local ready.
[2019-07-23 09:31:17,164: CRITICAL/MainProcess] Unrecoverable error: RuntimeError("Model class django_celery_results.models.TaskResult doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 115, in start
    self.on_start()
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 139, in on_start
    self.emit_banner()
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 154, in emit_banner
    ' \n', self.startup_info(artlines=not use_image))),
  File "/usr/local/lib/python3.7/site-packages/celery/apps/worker.py", line 217, in startup_info
    results=self.app.backend.as_uri(),
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 1205, in backend
    return self._get_backend()
  File "/usr/local/lib/python3.7/site-packages/celery/app/base.py", line 923, in _get_backend
    self.loader)
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 73, in by_url
    return by_name(backend, loader), url
  File "/usr/local/lib/python3.7/site-packages/celery/app/backends.py", line 53, in by_name
    cls = symbol_by_name(backend, aliases)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/__init__.py", line 4, in <module>
    from .database import DatabaseBackend
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/backends/database.py", line 6, in <module>
    from ..models import TaskResult
  File "/usr/local/lib/python3.7/site-packages/django_celery_results/models.py", line 18, in <module>
    class TaskResult(models.Model):
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 95, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django_celery_results.models.TaskResult doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[2019-07-23 09:33:10,126: INFO/MainProcess] Connected to redis://127.0.0.1:6379/11
[2019-07-23 09:33:10,139: INFO/MainProcess] mingle: searching for neighbors
[2019-07-23 09:33:11,165: INFO/MainProcess] mingle: all alone
[2019-07-23 09:33:11,200: WARNING/MainProcess] /usr/local/lib/python3.7/site-packages/celery/fixups/django.py:200: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn('Using settings.DEBUG leads to a memory leak, never '
[2019-07-23 09:33:11,200: INFO/MainProcess] celery@lwt.local ready.
[2019-07-23 09:33:30,185: INFO/MainProcess] Received task: users.tasks.test[2fb389da-e688-4f54-b7f0-cc7c590f02dd]  
[2019-07-23 09:33:30,235: INFO/ForkPoolWorker-1] Task users.tasks.test[2fb389da-e688-4f54-b7f0-cc7c590f02dd] succeeded in 0.045441395999997525s: 1
